stages:
  - validate

image:
  name: registry.gitlab.com/torese/docker-ansible

variables:
    ANSIBLE_HOST_KEY_CHECKING: 'false'
    ANSIBLE_FORCE_COLOR: 'true'
    ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3

before_script:
  - yum install httpd -y
  - yum install -y python3
  - ansible --version

validate:
  stage: validate
  script:
    - ansible-playbook initial-kubernetes.yaml --syntax-check