# Retrieve kubeconfig
- name: Copy, modify and retrieve kubeconfig for external access
  hosts: k3s-main-master
  become: true
  tasks:
    - ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /tmp/kubeconfig
        remote_src: yes
    - ansible.builtin.replace:
        path: /tmp/kubeconfig
        regexp: '127.0.0.1'
        replace: "{{ hostvars[groups['k3s-masters'][0]]['inventory_hostname'] }}"
    - ansible.builtin.fetch:
        src: /tmp/kubeconfig
        dest: ./fetched/kubeconfig
        flat: yes
    - ansible.builtin.file:
        path: /tmp/kubeconfig
        state: absent
# Install python3-pip
- name: install pre-requisites apt
  hosts: k3s-main-master
  become: true
  tasks:
    - ansible.builtin.apt:
        name: python3-pip
        state: present
    - ansible.builtin.apt:
        name: curl
        state: present
# Install python packages for kubernetes
- name: install pre-requisites pip
  hosts: k3s-main-master
  tasks:
    - pip:
        name:
          - pyyaml
          - kubernetes
# Deploy the current basic manifests
- name: Deploy basic manifests
  hosts: k3s-main-master
  tasks:
    - ansible.builtin.file:
        path: /tmp/ansible_files/kubernetes-manifests-devops
        state: directory
    - copy:
        src: ../kubernetes-manifests-devops/
        dest: /tmp/ansible_files/kubernetes-manifests-devops/
    - kubernetes.core.k8s:
        state: present
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        src: /tmp/ansible_files/kubernetes-manifests-devops/coredns.yaml
    - kubernetes.core.k8s:
        state: present
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        src: /tmp/ansible_files/kubernetes-manifests-devops/cloud-controller-manager.yaml
    - kubernetes.core.k8s:
        state: present
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        src: /tmp/ansible_files/kubernetes-manifests-devops/metrics-server-components.yaml
    - kubernetes.core.k8s:
        state: present
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        src: /tmp/ansible_files/kubernetes-manifests-devops/cluster-autoscaler.yaml
    - kubernetes.core.k8s:
        state: present
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        src: /tmp/ansible_files/kubernetes-manifests-devops/traefik.yaml

- name: Deploy traefik using helm
  hosts: k3s-main-master
  tasks:
    - ansible.builtin.shell:
        cmd: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    - kubernetes.core.helm_repository:
        name: traefik
        repo_url: "https://helm.traefik.io/traefik"
    - kubernetes.core.helm:
        name: traefik
        chart_ref: traefik/traefik
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        release_namespace: traefik
        update_repo_cache: true
        values_files:
          - /tmp/ansible_files/kubernetes-manifests-devops/traefik-values.yaml
    - copy:
        src: ../fullchain.pem
        dest: /tmp/ansible_files/fullchain.pem
    - copy:
        src: ../privkey.pem
        dest: /tmp/ansible_files/privkey.pem
    - ansible.builtin.shell:
        cmd: kubectl create secret generic traefik-cert --from-file=tls.crt=/tmp/ansible_files/fullchain.pem --from-file=tls.key=/tmp/ansible_files/privkey.pem -n traefik
    - kubernetes.core.k8s:
        state: present
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        src: /tmp/ansible_files/kubernetes-manifests-devops/traefik-dashboard.yaml

- name: Deploy kubernetes dashboard
  hosts: k3s-main-master
  tasks:
    - kubernetes.core.k8s:
        state: present
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        src: /tmp/ansible_files/kubernetes-manifests-devops/kubernetes-dashboard.yaml
    - ansible.builtin.shell:
        cmd: kubectl -n kubernetes-dashboard create token admin-user >> /tmp/ansible_files/token
    - ansible.builtin.fetch:
        src: /tmp/ansible_files/token
        dest: ./fetched/token
        flat: yes

- name: Deploy grafana dashboard
  hosts: k3s-main-master
  tasks:
    - ansible.builtin.file:
        path: /tmp/ansible_files/kubernetes-manifests-sre
        state: directory
    - copy:
        src: ../kubernetes-manifests-sre/
        dest: /tmp/ansible_files/kubernetes-manifests-sre/
    - kubernetes.core.k8s:
        state: present
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        src: /tmp/ansible_files/kubernetes-manifests-sre/monitoring.yml